// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FormPanel: typeof import('./src/components/formPanel/formPanel.vue')['default']
    MarkdownEditor: typeof import('./src/components/markdownEditor/markdownEditor.vue')['default']
    MarkDownEditor: typeof import('./src/components/markDownEditor/markDownEditor.vue')['default']
    Menus: typeof import('./src/components/menus/menus.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCascader: typeof import('naive-ui')['NCascader']
    NDialog: typeof import('naive-ui')['NDialog']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGradientText: typeof import('naive-ui')['NGradientText']
    NIcon: typeof import('naive-ui')['NIcon']
    NIconWrapper: typeof import('naive-ui')['NIconWrapper']
    NImage: typeof import('naive-ui')['NImage']
    NInput: typeof import('naive-ui')['NInput']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    NTreeSelect: typeof import('naive-ui')['NTreeSelect']
    PageContent: typeof import('./src/components/pageContent/pageContent.vue')['default']
    PageContentList: typeof import('./src/components/pageContentList/pageContentList.vue')['default']
    PageContentListItem: typeof import('./src/components/pageContentListItem/pageContentListItem.vue')['default']
    PnutAvatar: typeof import('./src/components/pnutAvatar/pnutAvatar.vue')['default']
    PnutFormDialog: typeof import('./src/components/pnutFormDialog/pnutFormDialog.vue')['default']
    PnutMenu: typeof import('./src/components/pnutMenu/pnutMenu.vue')['default']
    RightAside: typeof import('./src/components/rightAside/rightAside.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
